### PR TITLE
fix: Prevent premature line wrapping of plant name

### LINKED ISSUE #2: Styling issues lead to visual impairments
Browser: Google Chrome 136 (latest)

Image

The plant card's CSS leads to several visual problems. The name span does not use the full width of the available space (looking at the visual inspector, it starts at the left border of the parent box and not the right border of the image). Thus, the name line wraps before it is necessary.
Image

In the German translation, state is translated into the much longer word "Pflanzenzustand". This often leads to line wrapping in the species line. Since the container does not extend vertically, I end up with copy behind the attributes. I suggest using ellipsis here instead.
Image

### PR DESCRIPTION
**Pull request by gregor**
fixes #2

### CODE REVIEW

File: dist/fyta-plant-card.js [hunk 1]
```diff
@@ -563,8 +563,9 @@ class FytaPlantCard extends HTMLElement {
         font-weight: bold;
         width: calc(100% - 120px);
         margin-top: 8px;
-        text-transform: capitalize;
-        display: block;
+        text-wrap: nowrap;
+        text-overflow: ellipsis;
+        display: inline-block;
```
Comment (gregor) [inline dist/fyta-plant-card.js:568]: Fixes placement of name span for increased width to prevent premature wrapping

File: dist/fyta-plant-card.js [hunk 2]
```diff
@@ -563,8 +563,9 @@ class FytaPlantCard extends HTMLElement {
         font-weight: bold;
         width: calc(100% - 120px);
         margin-top: 8px;
-        text-transform: capitalize;
```
Comment (gregor) [inline dist/fyta-plant-card.js:566]: Do not change user values

File: dist/fyta-plant-card.js [hunk 3]
```diff
@@ -563,8 +563,9 @@ class FytaPlantCard extends HTMLElement {
...
-        display: block;
+        text-wrap: nowrap;
+        text-overflow: ellipsis;
```
Comment (gregor) [inline dist/fyta-plant-card.js:567]: Prevents line wraps altogether, even for very long names, and relies on ellipsis instead.

**Review by dontinelli — APPROVED** [review]
